#!/usr/bin/env bash

# Set personal aliases, overriding those provided by oh-my-zsh libs, plugins, and themes
# For a full list of active aliases, run `alias`.

# Unix
alias ll='ls -l'				# Long List
alias lla='ls -la'			# Long List All
alias l='ls -lFh'				# Long List by Size Show Human Readable
alias la='ls -lAFh'			# Long List Show all Human Readable
alias lt='ls -ltFh' 		# Long List By Date Show Human Readable
alias ldot='ls -ld .*'	# Long List Show "." files
alias tlf='tail -f'
alias ..='cd ..'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'

# Quick File Views / Edits
alias db='cd ~/Dropbox'
alias dl='cd ~/Downloads'
alias dd='cd ~/Desktop'
alias dw='cd ~/Workspace'
alias ea='$EDITOR ~/dotfiles/zsh/aliases'
alias ed='$EDITOR ~/dotfiles'
alias eh='$EDITOR /etc/hosts'
alias eo='$EDITOR ~/dotfiles/zsh/oh-my-zsh'
alias ez='$EDITOR ~/.zshrc'
alias hosts=eh
alias zshrc=ez

# OSX
alias saf='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder'
alias haf='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder'
alias flush='sudo killall -HUP mDNSResponder'

# GIT - https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gcm='git commit -m'
alias gac='git add -all && git commit -m'
alias gb='git branch'
alias gbd='git branch -d'
alias gd='git diff'
alias go='git checkout'
alias gom='git checkout master'
alias gob='git checkout -b'
alias gl='git pull'
alias gp='git push'
alias gpf='git push -f'
alias gpb='git push --set-upstream origin $(git_current_branch)'
alias gr='git rebase'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grm='git rebase master'
alias gri='git rebase -i'
alias grim='git rebase -i master'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias gcl='git clone'
alias gf='git fetch'
alias gl='git log --oneline --decorate --color --graph'
alias gla='git log --oneline --decorate --color --graph --all'
alias glo='git log --oneline --decorate --color'
alias glg='git log --stat --color'
alias glgg='git log --graph --color'
alias glga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glgp='git log --stat --color --patch'
alias glol='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gloa='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --all'

# Bundler
alias b='bundle'
alias be='bundle exec'
alias bef='bundle exec foreman start'
alias bi='bundle install'
alias bu='bundle update'

# Ruby
alias rbv='rbenv versions'
alias rbl='rbenv install -l'
alias rbi='rbenv install'

# Rails
alias rs='rails server'
alias rc='rails console'
alias rg='rails generate'
alias rgm='rails generate migration'
alias rdm='rake db:migrate'
alias rdr='rake db:rollback'
alias rdc='rake db:create'
alias rds='rake db:seed'
alias rdd='rake db:drop'
alias rdrs='rake db:reset'
alias rdtc='rake db:test:clone'
alias rdtp='rake db:test:prepare'
alias rdmtc='rake db:migrate db:test:clone'
alias rdsl='rake db:schema:load'
alias rr='rake routes'
alias rrg='rake routes | grep'
alias rt='rake test'

# NPM
alias npmg='npm i -g'
alias npms='npm i -S'
alias npmd='npm i -D'
alias npmo='npm outdated'
alias npml='npm list --depth=0'
alias npmgl='npm list -g --depth=0'

# Homebrew
alias brl='brew list -1'
alias brsl='brew services list'
alias brsr='brew services restart'
alias brs0='brew services stop'
alias brs1='brew services start'
alias brin='brew info'
alias bri='brew install'
alias bru='brew update'
alias brup='brew upgrade'
alias brupa='brew upgade --all'
alias brun='brew uninstall'

# Mac App Store (https://github.com/argon/mas)
# alias masi='mas install'
# alias masl='mas list'
# alias maso='mas outdated'
# alias mass='mas search'
# alias masu='mas upgrade'

# Misc
alias path='echo $PATH | tr -s ":" "\n"'
alias reload='source ~/.zshrc && echo "ZSH config reloaded from ~/.zshrc"'
alias reload!=reload
alias src=reload
