#!/usr/bin/env bash

set -e

source "${HOME}/.dotfiles/scripts/functions"

export DOTFILES_DIR="${HOME}/.dotfiles"

backup_files() {
  # Create Backup directory !found
  if [ ! -d $DOTFILES_DIR/backups ]; then
    mkdir $DOTFILES_DIR/backups
  fi

  # Grab all .files from 'system' directory
  files=$DOTFILES_DIR/system/.??*

  # For Each File, backup and create a symlink to new .file
  for file in $files; do 
    if [ ! -f $file ]; then
      return
    fi

    filename=$(basename $file)

    # Move original file to backup directory
    if [ -f $HOME/$filename ] && [ ! -L $HOME/$filename ]; then
      echo_nice "Backing up $filename to $DOTFILES_DIR/backups/$filename"
      mv $HOME/$filename $DOTFILES_DIR/backups/$filename
    fi

    # Link new dotfiles to home directory
    if [ ! -L $HOME/$filename ]; then
      echo_nice "Linking $filename to $DOTFILES_DIR/system/$filename"
      ln -sf $DOTFILES_DIR/system/$filename $HOME/$filename
    fi
  done
}

create_local_files() {
  if [ ! -f $DOTFILES_DIR/.zsh.local ] ; then
    echo "#!/usr/bin/env bash\n" >> $DOTFILES_DIR/.zsh.local
  fi
}

main() {
  backup_files
  create_local_files

  echo_green "Dotfiles are setup, checkout the $DOTFILES_DIR/.gitconfig.local and $DOTFILES_DIR/.zsh.local for custom settings"
}

main
