#!/usr/bin/env bash

set -e

source "${HOME}/.dotfiles/scripts/functions"

export DOTFILES_DIR="${HOME}/.dotfiles"

restore_files() {
  files=$DOTFILES_DIR/system/.??*

  for file in $files; do 
    if [ ! -f $file ]; then
      return
    fi

    filename=$(basename $file)

    # Unlink new dotfiles from home directory
    if [ -L $HOME/$filename ]; then
      echo_nice "Removing link for $filename"
      rm $HOME/$filename
    fi

    # Move original file back to home directory
    if [ -f $DOTFILES_DIR/backups/$filename ]; then
      echo_nice "Restoring Original file to $HOME/$filename"
      mv $DOTFILES_DIR/backups/$filename $HOME/$filename
    fi
  done
}

main() {
  restore_files
  echo_green "Make sure your files have been restored properly and then remove the $DOTFILES_DIR directory."
}

main
